name: GitHub Metrics

on:
  schedule:
    - cron: "0 3 * * *"   # daily at 3 AM UTC
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ArshiaRx

          # Core sections
          base: header, repositories

          # Language analytics
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

          # Repo highlights
          plugin_repositories: yes
          plugin_repositories_featured: LeetCode, CPS731_TrafficNewsApp, COE692_CarDealership_Project
